### ISSUE TITLE
Ionic v5 : Cannot to use ViewController

### ISSUE THREAD

**Issue by eureka0928** [AceBerry924/restaurant-ionic-app#2]
"export 'ViewController' was not found in '@ionic/angular'

ViewController shows error after Ionic v4 projects

What is wrong with this controller?

**Comment by fury0928** [comment]
I think the ViewController is deprecated from v4

What for you would need it? If you need it to close a modal for example, you could use the ModalController instead. Same for PopoverController

```
this.viewController.dismiss() ===> this.modalController.dismiss()
this.viewController.dismiss() ===> this.popoverController.dismiss()
```
